# Generated by Django 5.2.4 on 2025-07-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_note_points_note_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="points",
        ),
    ]
